version = "3.7.17"
runner.dialect = scala212

align.preset = none
assumeStandardLibraryStripMargin = false
binPack.literalArgumentLists = true
binPack.parentConstructors = false
continuationIndent.defnSite = 4
danglingParentheses.preset = true
docstrings.style = SpaceAsterisk
includeCurlyBraceInSelectChains = true
lineEndings = unix
maxColumn = 120
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly
newlines.afterCurlyLambdaParams = squash
optIn.breakChainOnFirstMethodDot = true
project.git = true
rewrite.rules = [ SortImports, PreferCurlyFors ]
spaces.afterKeywordBeforeParen = true

project.includeFilters = [".*\\.sbt$", ".*\\.scala$"]
project.excludeFilters = [".*\\.scala.html$", "target/.*", "modules/admin/target/.*"]
fileOverride {
  "glob:**/project/**" {
    runner.dialect = sbt1
  }
}
onTestFailure = "To fix this, run `scalafmt` within sbt or `sbt scalafmt` on the project base directory"
